name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: 'release-please-config.json'
          manifest-file: '.release-please-manifest.json'
