name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reggi/release-please-action@9f3798070f73fb90d2db1a5e44861d183a64b25a
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: 'release-please-config.json'
          manifest-file: '.release-please-manifest.json'
